version: '3.8'

services:
  wellness-cart-mysql:
    image: mysql:8.0
    restart: always
    container_name: wellness-cart-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: wellnesscart   # Auto-create database on first start
    ports:
      - "3310:3306"                 # Host port 3310 mapped to container 3306
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql   # Init script runs only on first container start (empty volume)
      - wellness-cart-mysql-data:/var/lib/mysql            # Persist MySQL data

  wellness-cart-redis:
    image: redis:latest
    container_name: wellness-cart-redis-container
    ports:
      - "6380:6379"               # Host port 6380 mapped to container 6379
    volumes:
      - wellness-cart-redis-data:/data
    restart: always

volumes:
  wellness-cart-redis-data:
  wellness-cart-mysql-data:
